# Generated by Django 2.2.4 on 2021-11-12 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
